# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_newhe_something'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewHe',
        ),
        migrations.RemoveField(
            model_name='something',
            name='album',
        ),
        migrations.RemoveField(
            model_name='something',
            name='band',
        ),
        migrations.DeleteModel(
            name='Something',
        ),
    ]
