# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models

import music.models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0006_auto_20160929_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to=music.models.update_filename),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to=music.models.update_filename),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to=music.models.update_filename),
        ),
    ]
