# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0007_auto_20160929_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='length',
            new_name='duration',
        ),
    ]
