# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0008_auto_20160929_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
