# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20160930_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='band',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default=''),
        ),
    ]
