# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20171211_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('band_id', models.IntegerField()),
            ],
        ),
    ]
