# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_likedbyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedbyuser',
            name='band_id',
        ),
        migrations.RemoveField(
            model_name='likedbyuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='likedbyuser',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Band'),
        ),
        migrations.AddField(
            model_name='likedbyuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
