# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20171216_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedbyusers',
            name='user',
            field=models.IntegerField(),
        ),
    ]
