# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20171203_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='language',
            field=models.ForeignKey(default='Unknown language', on_delete=django.db.models.deletion.CASCADE, to='music.Languages'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
