# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20171216_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedbyusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
