# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20171217_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='album',
            name='language',
        ),
        migrations.RemoveField(
            model_name='album',
            name='released_date',
        ),
    ]
