# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20171217_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
